name: unit-test
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
  push:
    branches: [main]
jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version-file: pyproject.toml
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Check the pyproject.toml and the poetry.lock file are consistent.
        run: poetry check
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Test with pytest
        run: poetry run  pytest -m 'not nightly' || ([ $? = 5 ] && exit 0 || exit $?)
